name: android tests, builds checks

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
  workflow_dispatch:
    
jobs:
#  lint: 
#    runs-on: ubuntu-latest
#    steps:
#     - name: check out code 
#       uses: actions/checkout@v2
      
#     - name: build application with gradle
#       run: ./gradlew lintDebug
      
#     - name: upload artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: build results
#         path: app/build/reports/lint-results-debug.html
        
#  unit-test:
#     needs: [lint]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v2

#       - name: Run tests
#         run: ./gradlew test

#       - name: Upload test report
#         uses: actions/upload-artifact@v2
#         with:
#           name: unit_test_report
#           path: app/build/reports/tests/testDebugUnitTest/
       
       
 instrumentation-test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: setup up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 6110076
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
          
          
#  static-code-analysis:
#     needs: [unit-test]
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v2
        
    

    
  
   
   
  

  
  
