name: android tests, builds checks

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
  workflow_dispatch:
    
jobs:

 instrumentation-test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
          
      - name: setup java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
          
          
          
          
          
#  lint: 
#    runs-on: ubuntu-latest
#    steps:
#     - name: check out code 
#       uses: actions/checkout@v2
      
#     - name: build application with gradle
#       run: ./gradlew lintDebug
      
#     - name: upload artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: build results
#         path: app/build/reports/lint-results-debug.html
        
#  unit-test:
#     needs: [lint]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v2

#       - name: Run tests
#         run: ./gradlew test

#       - name: Upload test report
#         uses: actions/upload-artifact@v2
#         with:
#           name: unit_test_report
#           path: app/build/reports/tests/testDebugUnitTest/
       
       

          
          
#  static-code-analysis:
#     needs: [instrumentation-test]
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v2
        
#       - name: setup jdk 1.8
#         uses: actions/setup-java@v2
#         with:
#          java-version: 1.8
         
#       - name: sonarCloud Scan
#         run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN}} 
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
        
    

    
  
   
   
  

  
  
