name: android tests, builds checks

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
  workflow_dispatch:
    
jobs:
 lint: 
   runs-on: ubuntu-latest
   steps:
    - name: check out code 
      uses: actions/checkout@v2
      
    - name: build application with gradle
      run: ./gradlew lintDebug
      
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build results
        path: app/build/reports/lint-results-debug.html
        
 unit-test:
   needs: [lint]
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: run unit tests
      run: .gradlew/ test
      
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: test results
       path: app/build/reports/tests/testDebugUnitTest/
   
   
  

  
  
